### ISSUE TITLE
Cannot find module 'jquery' from

### ISSUE THREAD

**Issue by croucha** [kenwheeler/slick#3349]
Hi there,

I'm using your plugin with NPM and gulp with browserify and I'm trying to require it in a build script like this:

`require('slick-carousel');`

And I get the following error:

{ Error: Cannot find module 'jquery' from 'C:\gitprojects\gctsportal\gcts-ui-artifacts\node_modules\slick-carousel\slick'
    at C:\gitprojects\gctsportal\gcts-ui-artifacts\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (C:\gitprojects\gctsportal\gcts-ui-artifacts\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\gitprojects\gctsportal\gcts-ui-artifacts\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\gitprojects\gctsportal\gcts-ui-artifacts\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\gitprojects\gctsportal\gcts-ui-artifacts\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\gitprojects\gctsportal\gcts-ui-artifacts\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)

Is my require statement incorrect?  I even tried this: require('slick-carousel')(window.$); to pass the module but had no luck.

Thanks,

Andre

**Comment by a-p-co** [comment]
Same here, any idea what it could be? just try to do a npm install and get this:

npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.

**Comment by croucha** [comment]
I think I understand what it is.  Since jquery is a peer depends in the package json, I think you have to npm install it globally first.  I'll try that later and let you know.

**Comment by a-p-co** [comment]
Thanks would be great!!! Thanks!
