### ISSUE TITLE
Cannot read property 'add' of undefined Using Angular 11.2.10

### ISSUE THREAD

**Issue by Kekay69** [kenwheeler/slick#4088]
> Using Angular 11.2.9 with a brand new project I got this error "Cannot read property 'add' of undefined"

====================================================================

[error] TypeError: Cannot read property 'add' of undefined
    at D:\My Laptop\Certifications\food-blog-eog\node_modules\@ngtools\webpack\src\ivy\plugin.js:164:86
    at Array.forEach (<anonymous>)
    at D:\My Laptop\Certifications\food-blog-eog\node_modules\@ngtools\webpack\src\ivy\plugin.js:164:33
    at SyncHook.eval [as call] (eval at create (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:11:1)
    at SyncHook.lazyCompileHook (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:630:30)
    at D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.compile (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:662:28)
    at D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._go (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Watching.js:41:32)
    at D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Watching.js:33:9
    at Compiler.readRecords (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:529:11)

====================================================================

#### Steps to reproduce the problem

1. ng new food-blog-eog
2. ng serve
3.  An unhandled exception occurred: Cannot read property 'add' of undefined
See "C:\Users\Enrique\AppData\Local\Temp\ng-82rUNC\angular-errors.log" for further details.

====================================================================

#### What is the expected behaviour?

Be able to see the compiled brand new project

====================================================================

#### What is observed behaviour?

No able to compile it.

====================================================================

#### More Details

- I have used command Prompt as first step to create the project with the above error results
- Using previous Angular versions  such as 8 or 9 I had no problem at all
- I am using:
Angular CLI: 11.2.9
Node: 14.15.4
OS: win32 x64

Angular: 11.2.10
... animations, common, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.9
@angular-devkit/build-angular   0.1102.9
@angular-devkit/core            11.2.9
@angular-devkit/schematics      11.2.9
@angular/cli                    11.2.9
@angular/compiler               11.2.11
@schematics/angular             11.2.9
@schematics/update              0.1102.9
rxjs                            6.6.7
typescript                      4.1.5
webpack                         5.34.0

**Comment by ubergeoff** [comment]
Hmmm - I can't see how this could be an Angular issue... since it worked in previous versions... then everything should work just fine in the newer versions.

However to try assist further.

Please see these example here:

https://www.flingo.co.za/slick/slick6

++ Please see source here: 

https://github.com/ubergeoff/flingo/blob/master/libs/slicker/src/lib/slicker.ts

**Comment by kapilSoni101** [comment]
@ubergeoff  sir are u fix above issue i am also facing above error in the angular 12 as well as 14 version?
